version: '3.8'

services:
  app:
    image: node:19 # You can choose your preferred Node.js version
    container_name: nextjs_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3001:3000" # Bind system port 3001 to container port 3000
    command: npm start # Assuming you use npm to start your app in dev mode
    environment:
      - NODE_ENV=production
    networks:
      - nextjs-network

networks:
  nextjs-network:
    driver: bridge