services:
  app:
    image: node:19
    container_name: nextjs_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3001:3000"
    command: npm start
    environment:
      - NODE_ENV=production
    networks:
      - nextjs-network

networks:
  nextjs-network:
    driver: bridge
